'use client'
import { FormEvent, useEffect, useState } from 'react'
import DayflowApp from '@/components/dayflow-app'

export default function AuthGate(){
 const [user,setUser]=useState<any>(undefined); const [mode,setMode]=useState<'login'|'register'>('login'); const [form,setForm]=useState({companyName:'',name:'',email:'',password:''}); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
 useEffect(()=>{fetch('/api/auth/session').then(r=>r.json()).then(d=>setUser(d.user||null))},[])
 if(user) return <DayflowApp user={user} onLogout={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null)}} />
 if(user===undefined) return <div className="grid min-h-screen place-items-center text-muted-foreground">Loading Dayflow…</div>
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');const endpoint=mode==='login'?'/api/auth/login':'/api/auth/register';const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setLoading(false);if(!r.ok){setMessage(d.error);return}if(mode==='register'){setMessage(d.devVerificationUrl?`Check your inbox. Local verification link: ${d.devVerificationUrl}`:'Check your inbox to verify your email.');setMode('login')}else setUser(d.user)}
 return <main className="grid min-h-screen place-items-center bg-background p-6"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-xl"><div className="mb-8 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground">D</div><div><p className="text-lg font-semibold">dayflow</p><p className="text-xs text-muted-foreground">Every workday, aligned.</p></div></div><h1 className="text-2xl font-semibold">{mode==='login'?'Welcome back':'Create your workspace'}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{mode==='login'?'Sign in to manage your people and operations.':'Register your company and invite your team.'}</p><form onSubmit={submit} className="mt-7 flex flex-col gap-4">{mode==='register'&&<><input required placeholder="Company name" value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"/><input required placeholder="Your full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"/></>}<input required type="email" placeholder="Work email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"/><input required minLength={8} type="password" placeholder="Password (8+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"/>{message&&<p className="break-words rounded-xl bg-muted p-3 text-xs leading-5 text-muted-foreground">{message}</p>}<button disabled={loading} className="h-11 rounded-xl bg-primary text-sm font-semibold text-primary-foreground disabled:opacity-60">{loading?'Please wait…':mode==='login'?'Sign in':'Create company'}</button></form><button onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('')}} className="mt-6 w-full text-sm text-primary hover:underline">{mode==='login'?"Don't have an account? Register your company":"Already registered? Sign in"}</button></div></main>
}
