'use client'

import { FormEvent, useEffect, useState } from 'react'
import { Eye, EyeOff } from 'lucide-react'
import DayflowApp from '@/components/dayflow-app'

type SessionUser = { name: string; email: string; role: string; companyName: string; mustChangePassword?: boolean }
export default function AuthGate() {
  const [user, setUser] = useState<SessionUser | null | undefined>(undefined); const [mode, setMode] = useState<'login' | 'register'>('login'); const [form, setForm] = useState({ companyName: '', name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const [showPassword, setShowPassword] = useState(false)
  useEffect(() => { fetch('/api/auth/session').then((response) => response.json()).then((result) => setUser(result.user || null)) }, [])
  if (user === undefined) return <div className="grid min-h-screen place-items-center text-muted-foreground">Loading Dayflow...</div>
  if (user) return user.mustChangePassword ? <ChangePassword onComplete={() => setUser({ ...user, mustChangePassword: false })} /> : <DayflowApp user={user} onLogout={async () => { await fetch('/api/auth/logout', { method: 'POST' }); setUser(null) }} />
  async function submit(event: FormEvent) { event.preventDefault(); const endpoint = mode === 'login' ? '/api/auth/login' : '/api/auth/register'; const response = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) { setMessage(result.error); return }; if (mode === 'register') { setMessage(result.devVerificationUrl ? `Verify your email: ${result.devVerificationUrl}` : 'Check your email to verify your account.'); setMode('login') } else setUser(result.user) }
  return <main className="grid min-h-screen place-items-center bg-background p-6"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-xl"><div className="mb-8 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground">D</div><div><p className="text-lg font-semibold">dayflow</p><p className="text-xs text-muted-foreground">Every workday, aligned.</p></div></div><h1 className="text-2xl font-semibold">{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h1><p className="mt-2 text-sm text-muted-foreground">{mode === 'login' ? 'Sign in with your email or Login ID.' : 'Register your company workspace.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode === 'register' && <><input required placeholder="Company name" value={form.companyName} onChange={(event) => setForm({ ...form, companyName: event.target.value })} className="h-11 w-full rounded-xl border bg-background px-3 text-sm" /><input required placeholder="Your full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="h-11 w-full rounded-xl border bg-background px-3 text-sm" /></>}<input required type="text" placeholder="Email or Login ID" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="h-11 w-full rounded-xl border bg-background px-3 text-sm" /><PasswordInput value={form.password} onChange={(value) => setForm({ ...form, password: value })} show={showPassword} setShow={setShowPassword} placeholder="Password (8+ characters)" />{message && <p className="break-all rounded-xl bg-muted p-3 text-xs text-muted-foreground">{message}</p>}<button className="h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">{mode === 'login' ? 'Sign in' : 'Create company'}</button></form><button onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage('') }} className="mt-5 w-full text-sm text-muted-foreground">{mode === 'login' ? 'Need a workspace? Create one' : 'Already have an account? Sign in'}</button></div></main>
}

function PasswordInput({ value, onChange, show, setShow, placeholder }: { value: string; onChange: (value: string) => void; show: boolean; setShow: (show: boolean) => void; placeholder: string }) { return <div className="relative"><input required minLength={8} type={show ? 'text' : 'password'} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 pr-11 text-sm" /><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div> }
function ChangePassword({ onComplete }: { onComplete: () => void }) { const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/auth/password', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ password }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return }; onComplete() } return <main className="grid min-h-screen place-items-center bg-background p-6"><form onSubmit={submit} className="w-full max-w-md space-y-4 rounded-3xl border border-border bg-card p-8 shadow-xl"><h1 className="text-2xl font-semibold">Set your password</h1><p className="text-sm text-muted-foreground">Replace your temporary password before continuing.</p>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<PasswordInput value={password} onChange={setPassword} show={show} setShow={setShow} placeholder="New password (8+ characters)" /><button className="h-11 w-full rounded-xl bg-primary text-sm font-semibold text-primary-foreground">Update password</button></form></main> }