'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bell, CalendarDays, ChevronDown, CircleDollarSign, Clock3, FileText, LayoutDashboard, Menu, Package, Plus, Search, Settings, ShieldCheck, Sparkles, Users, WalletCards, X } from 'lucide-react'

type User = { name: string; role: string; companyName: string }
type Employee = { id: string; employeeId: string; name: string; role: string; designation?: string; department?: string; checkIn?: string; checkOut?: string }
type Leave = { id: number; name: string; leaveType: string; startDate: string; endDate: string; remarks?: string; status: string }
type Dashboard = { date: string; employees: Employee[]; leaves: Leave[]; trend: { date: string; present: number; total: number }[]; metrics: { totalEmployees: number; presentToday: number; onLeaveToday: number; pendingApprovals: number }; ownAttendance?: Employee }
const nav = [['Overview', LayoutDashboard], ['Employees', Users], ['Attendance', Clock3], ['Leave', CalendarDays], ['Payroll', WalletCards], ['Recruitment', Sparkles], ['Performance', ShieldCheck], ['Assets', Package], ['Expenses', CircleDollarSign], ['Reports', FileText]] as const

function initials(name: string) { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) }
function formatTime(value?: string) { return value ? new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(`1970-01-01T${value}:00`)) : 'Not recorded' }

export default function DayflowApp({ user, onLogout }: { user: User; onLogout?: () => void }) {
  const [active, setActive] = useState('Overview'); const [query, setQuery] = useState(''); const [menuOpen, setMenuOpen] = useState(false)
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [showLeaveForm, setShowLeaveForm] = useState(false)
  const [leaveForm, setLeaveForm] = useState({ leaveType: 'Paid leave', startDate: '', endDate: '', remarks: '' })
  async function load() { const response = await fetch('/api/dashboard', { cache: 'no-store' }); if (!response.ok) { setError('Unable to load workspace data.'); return }; setData(await response.json()) }
  useEffect(() => { load(); const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer) }, [])
  async function mutate(body: object) { setError(''); const response = await fetch('/api/dashboard', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error || 'Unable to update workspace.'); return }; await load() }
  const filtered = useMemo(() => data?.employees.filter((employee) => `${employee.name} ${employee.department || ''} ${employee.designation || ''}`.toLowerCase().includes(query.toLowerCase())) || [], [data, query])
  const canApprove = ['admin', 'hr', 'manager'].includes(user.role); const ownAttendance = data?.ownAttendance
  if (!data) return <div className="grid min-h-screen place-items-center text-muted-foreground">Loading workspace data...</div>
  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-border/70 bg-card px-4 py-5 transition-transform lg:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between px-3"><div className="flex items-center gap-2.5"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><span className="text-lg font-semibold">dayflow</span></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setMenuOpen(false)}><X className="size-5" /></button></div><div className="mt-8 flex flex-1 flex-col gap-1">{nav.map(([label, Icon]) => <button key={label} onClick={() => { setActive(label); setMenuOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${active === label ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-[18px]" />{label}{label === 'Leave' && data.metrics.pendingApprovals > 0 && <span className="ml-auto rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700">{data.metrics.pendingApprovals}</span>}</button>)}</div><div className="border-t border-border/70 pt-4"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><Settings className="size-[18px]" />Settings</button><div className="mt-3 flex items-center gap-3 rounded-xl bg-muted/60 p-3"><div className="grid size-9 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{initials(user.name)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user.name}</p><p className="truncate text-xs capitalize text-muted-foreground">{user.role}</p></div><button aria-label="Sign out" onClick={onLogout}><X className="size-4 text-muted-foreground" /></button></div></div></aside>
    {menuOpen && <button aria-label="Close menu" className="fixed inset-0 z-20 bg-foreground/20 lg:hidden" onClick={() => setMenuOpen(false)} />}<div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-border/70 bg-background/90 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="lg:hidden" onClick={() => setMenuOpen(true)}><Menu className="size-5" /></button><div className="hidden items-center gap-2 text-sm text-muted-foreground md:flex"><span>{user.companyName}</span><ChevronDown className="size-4" /></div></div><div className="flex items-center gap-2"><button aria-label="Notifications" className="rounded-xl p-2.5 text-muted-foreground hover:bg-muted"><Bell className="size-[18px]" /></button><div className="mx-1 h-6 w-px bg-border" /><span className="hidden text-sm font-medium sm:block">{user.name}</span><div className="grid size-8 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{initials(user.name)}</div></div></header><main className="mx-auto max-w-[1440px] p-5 md:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">{formatDate(data.date)}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight md:text-4xl">Good morning, {user.name.split(' ')[0]}</h1><p className="mt-2 text-muted-foreground">Live workplace operations for {user.companyName}.</p></div><button onClick={() => mutate({ action: ownAttendance?.checkIn && !ownAttendance.checkOut ? 'check-out' : 'check-in' })} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium shadow-sm ${ownAttendance?.checkIn && !ownAttendance.checkOut ? 'bg-emerald-100 text-emerald-700' : 'bg-primary text-primary-foreground'}`}><Clock3 className="size-4" />{ownAttendance?.checkIn && !ownAttendance.checkOut ? 'Check out' : ownAttendance?.checkOut ? `Completed at ${formatTime(ownAttendance.checkOut)}` : 'Check in for today'}</button></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{active === 'Overview' ? <Overview data={data} filtered={filtered} query={query} setQuery={setQuery} setActive={setActive} mutate={mutate} canApprove={canApprove} setShowLeaveForm={setShowLeaveForm} /> : <Module active={active} data={data} filtered={filtered} mutate={mutate} canApprove={canApprove} setShowLeaveForm={setShowLeaveForm} />}</main></div>
    {showLeaveForm && <LeaveForm value={leaveForm} setValue={setLeaveForm} onClose={() => setShowLeaveForm(false)} onSubmit={async () => { await mutate({ action: 'leave-request', ...leaveForm }); setLeaveForm({ leaveType: 'Paid leave', startDate: '', endDate: '', remarks: '' }); setShowLeaveForm(false) }} />}
  </div>
}

function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Users }) { return <div className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><Icon className="size-5 text-primary" /></div></div> }
function Overview({ data, filtered, query, setQuery, setActive, mutate, canApprove, setShowLeaveForm }: { data: Dashboard; filtered: Employee[]; query: string; setQuery: (value: string) => void; setActive: (value: string) => void; mutate: (body: object) => Promise<void>; canApprove: boolean; setShowLeaveForm: (value: boolean) => void }) { return <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total employees" value={data.metrics.totalEmployees} icon={Users} /><Metric label="Present today" value={data.metrics.presentToday} icon={Clock3} /><Metric label="On leave today" value={data.metrics.onLeaveToday} icon={CalendarDays} /><Metric label="Pending approvals" value={data.metrics.pendingApprovals} icon={ShieldCheck} /></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><EmployeeTable employees={filtered} query={query} setQuery={setQuery} /><LeavePanel leaves={data.leaves.slice(0, 3)} setActive={setActive} mutate={mutate} canApprove={canApprove} setShowLeaveForm={setShowLeaveForm} /></div><div className="mt-6 rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><h2 className="font-semibold">Attendance, last seven days</h2><div className="mt-6 flex h-32 items-end gap-2">{data.trend.map((day) => <div key={day.date} className="flex flex-1 flex-col items-center gap-2"><div className="w-full max-w-12 rounded-t-md bg-primary/70" style={{ height: `${day.total ? Math.max(4, day.present / day.total * 100) : 4}%` }} /><span className="text-[10px] text-muted-foreground">{new Date(`${day.date}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short' })}</span></div>)}</div></div></> }

function EmployeeTable({ employees, query, setQuery }: { employees: Employee[]; query: string; setQuery: (value: string) => void }) { return <section className="rounded-2xl border border-border/70 bg-card shadow-sm"><div className="flex flex-col gap-3 border-b border-border/70 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Team overview</h2><p className="mt-1 text-sm text-muted-foreground">Current attendance from your workspace</p></div><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people" className="h-9 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm sm:w-48" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-border/70">{employees.map((employee) => <tr key={employee.id}><td className="px-5 py-3.5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-muted text-xs font-semibold">{initials(employee.name)}</div><div><p className="font-medium">{employee.name}</p><p className="text-xs text-muted-foreground">{employee.designation || employee.role}</p></div></div></td><td className="px-5 py-3.5 text-muted-foreground">{employee.department || 'Unassigned'}</td><td className="px-5 py-3.5"><span className={employee.checkIn ? 'text-emerald-600' : 'text-muted-foreground'}>{employee.checkIn ? 'Present' : 'Not checked in'}</span></td></tr>)}</tbody></table>{!employees.length && <p className="p-8 text-center text-sm text-muted-foreground">No employees match this search.</p>}</div></section> }

function LeavePanel({ leaves, setActive, mutate, canApprove, setShowLeaveForm }: { leaves: Leave[]; setActive: (value: string) => void; mutate: (body: object) => Promise<void>; canApprove: boolean; setShowLeaveForm: (value: boolean) => void }) { return <section className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Leave requests</h2><p className="mt-1 text-sm text-muted-foreground">Live requests from your team</p></div><button onClick={() => setActive('Leave')} className="text-sm font-medium text-primary">View all</button></div><div className="mt-5 flex flex-col gap-4">{leaves.map((leave) => <div key={leave.id} className="rounded-xl border border-border/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{leave.name}</p><p className="text-xs text-muted-foreground">{leave.leaveType} · {formatDate(leave.startDate)} - {formatDate(leave.endDate)}</p></div><span className="rounded-full bg-muted px-2 py-1 text-[11px] font-medium capitalize">{leave.status}</span></div>{leave.status === 'pending' && canApprove && <div className="mt-4 flex gap-2"><button onClick={() => mutate({ action: 'leave-status', id: leave.id, status: 'approved' })} className="flex-1 rounded-lg bg-primary py-2 text-xs font-medium text-primary-foreground">Approve</button><button onClick={() => mutate({ action: 'leave-status', id: leave.id, status: 'rejected' })} className="flex-1 rounded-lg border border-border py-2 text-xs font-medium">Reject</button></div>}</div>)}</div><button onClick={() => setShowLeaveForm(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-border py-2.5 text-sm text-muted-foreground"><Plus className="size-4" />New leave request</button></section> }

function Module({ active, data, filtered, mutate, canApprove, setShowLeaveForm }: { active: string; data: Dashboard; filtered: Employee[]; mutate: (body: object) => Promise<void>; canApprove: boolean; setShowLeaveForm: (value: boolean) => void }) { if (active === 'Employees' || active === 'Attendance') return <div className="mt-8"><EmployeeTable employees={filtered} query="" setQuery={() => undefined} /></div>; if (active === 'Leave') return <div className="mt-8"><LeavePanel leaves={data.leaves} setActive={() => undefined} mutate={mutate} canApprove={canApprove} setShowLeaveForm={setShowLeaveForm} /></div>; return <div className="mt-10 rounded-2xl border border-dashed border-border bg-card p-12 text-center"><FileText className="mx-auto size-8 text-primary" /><h2 className="mt-4 text-xl font-semibold">{active}</h2><p className="mt-2 text-sm text-muted-foreground">This module is ready for records from your workspace.</p></div> }
function LeaveForm({ value, setValue, onClose, onSubmit }: { value: { leaveType: string; startDate: string; endDate: string; remarks: string }; setValue: (value: { leaveType: string; startDate: string; endDate: string; remarks: string }) => void; onClose: () => void; onSubmit: () => Promise<void> }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-foreground/30 p-5"><form onSubmit={(event) => { event.preventDefault(); onSubmit() }} className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">New leave request</h2><button type="button" aria-label="Close" onClick={onClose}><X className="size-5" /></button></div><div className="mt-5 flex flex-col gap-3"><input required placeholder="Leave type" value={value.leaveType} onChange={(event) => setValue({ ...value, leaveType: event.target.value })} className="h-11 rounded-xl border border-input bg-background px-3 text-sm" /><input required type="date" value={value.startDate} onChange={(event) => setValue({ ...value, startDate: event.target.value })} className="h-11 rounded-xl border border-input bg-background px-3 text-sm" /><input required type="date" value={value.endDate} onChange={(event) => setValue({ ...value, endDate: event.target.value })} className="h-11 rounded-xl border border-input bg-background px-3 text-sm" /><textarea placeholder="Reason (optional)" value={value.remarks} onChange={(event) => setValue({ ...value, remarks: event.target.value })} className="min-h-20 rounded-xl border border-input bg-background p-3 text-sm" /></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-sm">Cancel</button><button className="rounded-xl bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Submit request</button></div></form></div> }