'use client'

import { useMemo, useState } from 'react'
import { Bell, CalendarDays, ChevronDown, CircleDollarSign, Clock3, FileText, LayoutDashboard, LogOut, Menu, MoreHorizontal, Package, Plus, Search, Settings, ShieldCheck, Sparkles, UserRound, Users, WalletCards, X } from 'lucide-react'

const people = [
  { name: 'Alex Morgan', role: 'Head of People', team: 'Operations', status: 'Present', initials: 'AM', tone: 'bg-primary text-primary-foreground' },
  { name: 'Priya Shah', role: 'HR Business Partner', team: 'People', status: 'Present', initials: 'PS', tone: 'bg-sky-100 text-sky-700' },
  { name: 'Jordan Lee', role: 'Product Designer', team: 'Engineering', status: 'On leave', initials: 'JL', tone: 'bg-amber-100 text-amber-700' },
  { name: 'Maya Wilson', role: 'Marketing Lead', team: 'Marketing', status: 'Present', initials: 'MW', tone: 'bg-rose-100 text-rose-700' },
  { name: 'Noah Williams', role: 'Engineering Manager', team: 'Engineering', status: 'Present', initials: 'NW', tone: 'bg-violet-100 text-violet-700' },
]

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Employees', icon: Users }, { label: 'Attendance', icon: Clock3 }, { label: 'Leave', icon: CalendarDays }, { label: 'Payroll', icon: WalletCards }, { label: 'Recruitment', icon: Sparkles }, { label: 'Performance', icon: ShieldCheck }, { label: 'Assets', icon: Package }, { label: 'Expenses', icon: CircleDollarSign }, { label: 'Reports', icon: FileText },
]

function Metric({ label, value, detail, icon: Icon, accent }: { label: string; value: string; detail: string; icon: typeof Users; accent: string }) {
  return <div className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p></div><div className={`flex size-10 items-center justify-center rounded-xl ${accent}`}><Icon className="size-5" /></div></div><p className="mt-4 text-xs text-muted-foreground"><span className="font-medium text-emerald-600">{detail.split(' ')[0]}</span>{' '}{detail.split(' ').slice(1).join(' ')}</p></div>
}

export default function DayflowApp({ user, onLogout }: { user?: { name: string; role: string; companyName: string }; onLogout?: () => void }) {
  const [active, setActive] = useState('Overview')
  const [query, setQuery] = useState('')
  const [menuOpen, setMenuOpen] = useState(false)
  const [checkedIn, setCheckedIn] = useState(false)
  const [leaveRequests, setLeaveRequests] = useState([{ name: 'Jordan Lee', type: 'Paid leave', dates: 'Aug 25 – Aug 27', status: 'Pending' }, { name: 'Maya Wilson', type: 'Sick leave', dates: 'Aug 19 – Aug 20', status: 'Approved' }])
  const filteredPeople = useMemo(() => people.filter((person) => `${person.name} ${person.team} ${person.role}`.toLowerCase().includes(query.toLowerCase())), [query])

  function handleLeave(status: 'Approved' | 'Rejected') { setLeaveRequests((items) => items.map((item, index) => index === 0 ? { ...item, status } : item)) }

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-border/70 bg-card px-4 py-5 transition-transform lg:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-3"><div className="flex items-center gap-2.5"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><span className="text-lg font-semibold tracking-tight">dayflow</span></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setMenuOpen(false)}><X className="size-5" /></button></div>
      <div className="mt-8 flex flex-1 flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMenuOpen(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active === label ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-[18px]" />{label}{label === 'Leave' && <span className="ml-auto rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700">3</span>}</button>)}</div>
      <div className="border-t border-border/70 pt-4"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><Settings className="size-[18px]" />Settings</button><div className="mt-3 flex items-center gap-3 rounded-xl bg-muted/60 p-3"><div className="flex size-9 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">AM</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Alex Morgan</p><p className="truncate text-xs text-muted-foreground">Administrator</p></div><MoreHorizontal className="size-4 text-muted-foreground" /></div></div>
    </aside>
    {menuOpen && <button aria-label="Close menu" className="fixed inset-0 z-20 bg-foreground/20 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-border/70 bg-background/90 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="lg:hidden" onClick={() => setMenuOpen(true)}><Menu className="size-5" /></button><div className="hidden items-center gap-2 text-sm text-muted-foreground md:flex"><span>{user?.companyName || 'Workspace'}</span><ChevronDown className="size-4" /></div></div><div className="flex items-center gap-2"><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-muted-foreground hover:bg-muted"><Bell className="size-[18px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-primary" /></button><div className="mx-1 h-6 w-px bg-border" /><button className="flex items-center gap-2 rounded-xl p-1.5 pr-2 hover:bg-muted"><div className="flex size-8 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">AM</div><span className="hidden text-sm font-medium sm:block">Alex Morgan</span><ChevronDown className="hidden size-4 text-muted-foreground sm:block" /></button></div></header>
      <main className="mx-auto max-w-[1440px] p-5 md:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Friday, August 22, 2026</p><h1 className="mt-1 text-3xl font-semibold tracking-tight md:text-4xl">Good morning, Alex</h1><p className="mt-2 text-muted-foreground">Here&apos;s what&apos;s happening across your workplace today.</p></div><button onClick={() => setCheckedIn((value) => !value)} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium shadow-sm transition ${checkedIn ? 'bg-emerald-100 text-emerald-700' : 'bg-primary text-primary-foreground hover:opacity-90'}`}><Clock3 className="size-4" />{checkedIn ? 'Checked in at 9:02 AM' : 'Check in for today'}</button></div>
        {active !== 'Overview' ? <SectionPlaceholder active={active} /> : <>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total employees" value="128" detail="+8% from last month" icon={Users} accent="bg-primary/10 text-primary" /><Metric label="Present today" value="112" detail="87.5% attendance rate" icon={Clock3} accent="bg-emerald-100 text-emerald-700" /><Metric label="On leave today" value="09" detail="2 fewer than yesterday" icon={CalendarDays} accent="bg-amber-100 text-amber-700" /><Metric label="Pending approvals" value="07" detail="Requires your attention" icon={ShieldCheck} accent="bg-sky-100 text-sky-700" /></div>
        <div className="mt-8 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-2xl border border-border/70 bg-card shadow-sm"><div className="flex flex-col gap-3 border-b border-border/70 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Team overview</h2><p className="mt-1 text-sm text-muted-foreground">Your team&apos;s current status</p></div><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search people" className="h-9 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring sm:w-48" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Employee</th><th className="px-5 py-3 font-medium">Department</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium" /></tr></thead><tbody className="divide-y divide-border/70">{filteredPeople.map((person) => <tr key={person.name} className="hover:bg-muted/30"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><div className={`flex size-9 items-center justify-center rounded-full text-xs font-semibold ${person.tone}`}>{person.initials}</div><div><p className="font-medium">{person.name}</p><p className="text-xs text-muted-foreground">{person.role}</p></div></div></td><td className="px-5 py-3.5 text-muted-foreground">{person.team}</td><td className="px-5 py-3.5"><span className={`inline-flex items-center gap-1.5 text-xs font-medium ${person.status === 'Present' ? 'text-emerald-600' : 'text-amber-600'}`}><span className="size-1.5 rounded-full bg-current" />{person.status}</span></td><td className="px-5 py-3.5 text-right"><button aria-label={`More actions for ${person.name}`} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table></div><button onClick={() => setActive('Employees')} className="flex w-full items-center justify-center gap-2 border-t border-border/70 py-3 text-sm font-medium text-primary hover:bg-muted/40">View all employees <span aria-hidden="true">→</span></button></section>
        <section className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Leave requests</h2><p className="mt-1 text-sm text-muted-foreground">Review and take action</p></div><button onClick={() => setActive('Leave')} className="text-sm font-medium text-primary">View all</button></div><div className="mt-5 flex flex-col gap-4">{leaveRequests.map((request, index) => <div key={`${request.name}-${index}`} className="rounded-xl border border-border/70 p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-muted text-xs font-semibold">{request.name.split(' ').map((n) => n[0]).join('')}</div><div><p className="text-sm font-medium">{request.name}</p><p className="text-xs text-muted-foreground">{request.type} · {request.dates}</p></div></div><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${request.status === 'Pending' ? 'bg-amber-100 text-amber-700' : request.status === 'Approved' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'}`}>{request.status}</span></div>{request.status === 'Pending' && <div className="mt-4 flex gap-2"><button onClick={() => handleLeave('Approved')} className="flex-1 rounded-lg bg-primary py-2 text-xs font-medium text-primary-foreground">Approve</button><button onClick={() => handleLeave('Rejected')} className="flex-1 rounded-lg border border-border py-2 text-xs font-medium hover:bg-muted">Reject</button></div>}</div>)}</div><button onClick={() => setActive('Leave')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-border py-2.5 text-sm text-muted-foreground hover:bg-muted/40"><Plus className="size-4" />New leave request</button></section></div>
        <div className="mt-6 grid gap-6 md:grid-cols-2"><section className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Attendance trend</h2><p className="mt-1 text-sm text-muted-foreground">Last 7 working days</p></div><button aria-label="Attendance options" className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-4" /></button></div><div className="mt-6 flex h-32 items-end gap-2 sm:gap-4">{[68,82,74,92,86,96,88].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full max-w-9 rounded-t-md ${index === 5 ? 'bg-primary' : 'bg-primary/15'}`} style={{ height: `${height}%` }} /><span className="text-[10px] text-muted-foreground">{['M','T','W','T','F','M','T'][index]}</span></div>)}</div></section><section className="rounded-2xl border border-border/70 bg-primary p-5 text-primary-foreground shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-primary-foreground/70">Upcoming payroll</p><h2 className="mt-2 text-2xl font-semibold">September 01, 2026</h2></div><div className="flex size-10 items-center justify-center rounded-xl bg-primary-foreground/15"><WalletCards className="size-5" /></div></div><p className="mt-8 text-sm text-primary-foreground/75">Payroll processing starts in 6 working days.</p><button onClick={() => setActive('Payroll')} className="mt-4 rounded-lg bg-primary-foreground px-3 py-2 text-sm font-medium text-primary hover:opacity-90">Review payroll</button></section></div></>}
      </main></div>
  </div>
}

function SectionPlaceholder({ active }: { active: string }) { return <div className="mt-10 rounded-2xl border border-dashed border-border bg-card p-12 text-center shadow-sm"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><FileText className="size-6" /></div><h2 className="mt-4 text-xl font-semibold">{active}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">This workspace is connected to the Dayflow SQLite data layer. Manage {active.toLowerCase()} records, approvals, and reports from this dedicated module.</p><button className="mt-6 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground"><Plus className="size-4" />Create new {active.toLowerCase().replace(/s$/, '')}</button></div> }
