import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { z } from 'zod'
import { readSession } from '@/lib/auth'
import db from '@/lib/db'

const schema = z.object({ phone: z.string().max(40).optional(), address: z.string().max(300).optional(), profilePictureUrl: z.string().url().or(z.literal('')).optional(), personalEmail: z.string().email().or(z.literal('')).optional(), gender: z.string().max(30).optional(), maritalStatus: z.string().max(30).optional(), about: z.string().max(1000).optional(), skills: z.string().max(500).optional(), jobLove: z.string().max(500).optional(), certifications: z.string().max(500).optional(), interests: z.string().max(500).optional() })
async function session() { return readSession((await cookies()).get('dayflow_session')?.value) }
export async function GET() { const user = await session(); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const profile = db.prepare(`SELECT u.name,u.email,u.employee_id loginId,u.role,p.* FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id=?`).get(user.id); return NextResponse.json({ profile }) }
export async function PATCH(request: Request) { const user = await session(); if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: 'Invalid profile details.' }, { status: 400 }); const data = parsed.data; const fields = user.role === 'admin' ? data : { phone: data.phone, address: data.address, profilePictureUrl: data.profilePictureUrl }; const profile = db.prepare('SELECT user_id FROM profiles WHERE user_id=?').get(user.id); if (!profile) db.prepare('INSERT INTO profiles (user_id) VALUES (?)').run(user.id); db.prepare(`UPDATE profiles SET phone=?,address=?,profile_picture_url=?,personal_email=?,gender=?,marital_status=?,about=?,skills=?,job_love=?,certifications=?,interests=? WHERE user_id=?`).run(fields.phone || null, fields.address || null, fields.profilePictureUrl || null, fields.personalEmail || null, fields.gender || null, fields.maritalStatus || null, fields.about || null, fields.skills || null, fields.jobLove || null, fields.certifications || null, fields.interests || null, user.id); return NextResponse.json({ ok: true }) }